language: python
python:
    - 3.4
    - 3.5
    - pypy

# command to install dependencies
install: "pip install -r requirements.txt"

script:
    - ./setup.py install --root=/tmp/install-root
    - ./tests/run.py 
